// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const activityTags = `-- name: ActivityTags :many
SELECT DISTINCT unnest(tags)::text AS tag FROM activities ORDER BY tag
`

func (q *Queries) ActivityTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, activityTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (subject_kind, subject_id, kind, status, title, description, remediation, proof,
                        facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error,
                        ref, data, meta, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id, subject_kind, subject_id, kind, status, title, description, remediation, proof, facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error, ref, data, meta, started_at, finished_at, created_at, updated_at
`

type CreateActivityParams struct {
	SubjectKind string          `json:"subjectKind"`
	SubjectID   int64           `json:"subjectId"`
	Kind        string          `json:"kind"`
	Status      string          `json:"status"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Remediation string          `json:"remediation"`
	Proof       string          `json:"proof"`
	Facts       json.RawMessage `json:"facts"`
	Tags        []string        `json:"tags"`
	Origin      string          `json:"origin"`
	FlowID      string          `json:"flowId"`
	FlowTitle   string          `json:"flowTitle"`
	ProcessID   int64           `json:"processId"`
	Pid         string          `json:"pid"`
	ContextID   string          `json:"contextId"`
	Error       string          `json:"error"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
	StartedAt   *time.Time      `json:"startedAt"`
	FinishedAt  *time.Time      `json:"finishedAt"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.Remediation,
		arg.Proof,
		arg.Facts,
		arg.Tags,
		arg.Origin,
		arg.FlowID,
		arg.FlowTitle,
		arg.ProcessID,
		arg.Pid,
		arg.ContextID,
		arg.Error,
		arg.Ref,
		arg.Data,
		arg.Meta,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Remediation,
		&i.Proof,
		&i.Facts,
		&i.Tags,
		&i.Origin,
		&i.FlowID,
		&i.FlowTitle,
		&i.ProcessID,
		&i.Pid,
		&i.ContextID,
		&i.Error,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivitiesBySubject = `-- name: DeleteActivitiesBySubject :exec
DELETE FROM activities WHERE subject_kind = $1 AND subject_id = $2
`

type DeleteActivitiesBySubjectParams struct {
	SubjectKind string `json:"subjectKind"`
	SubjectID   int64  `json:"subjectId"`
}

func (q *Queries) DeleteActivitiesBySubject(ctx context.Context, arg DeleteActivitiesBySubjectParams) error {
	_, err := q.db.Exec(ctx, deleteActivitiesBySubject, arg.SubjectKind, arg.SubjectID)
	return err
}

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities WHERE id = $1
`

func (q *Queries) DeleteActivity(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteActivity, id)
	return err
}

const getActivity = `-- name: GetActivity :one
SELECT id, subject_kind, subject_id, kind, status, title, description, remediation, proof, facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error, ref, data, meta, started_at, finished_at, created_at, updated_at FROM activities WHERE id = $1
`

func (q *Queries) GetActivity(ctx context.Context, id int64) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Remediation,
		&i.Proof,
		&i.Facts,
		&i.Tags,
		&i.Origin,
		&i.FlowID,
		&i.FlowTitle,
		&i.ProcessID,
		&i.Pid,
		&i.ContextID,
		&i.Error,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, subject_kind, subject_id, kind, status, title, description, remediation, proof, facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error, ref, data, meta, started_at, finished_at, created_at, updated_at FROM activities
WHERE ($1::text = '' OR subject_kind = $1::text)
  AND ($2::bigint = 0 OR subject_id = $2::bigint)
  AND ($3::text = '' OR kind = $3::text)
  AND ($4::text = '' OR status = $4::text)
  AND ($5::text = '' OR flow_id = $5::text)
  AND (cardinality($6::text[]) = 0
       OR ($7::bool AND tags @> $6::text[])
       OR (NOT $7::bool AND tags && $6::text[]))
  AND ($8::text = ''
       OR title ILIKE '%' || $8::text || '%'
       OR description ILIKE '%' || $8::text || '%'
       OR remediation ILIKE '%' || $8::text || '%'
       OR flow_title ILIKE '%' || $8::text || '%'
       OR origin ILIKE '%' || $8::text || '%')
ORDER BY created_at DESC
LIMIT $9::int
`

type ListActivitiesParams struct {
	SubjectKind string   `json:"subjectKind"`
	SubjectID   int64    `json:"subjectId"`
	Kind        string   `json:"kind"`
	Status      string   `json:"status"`
	FlowID      string   `json:"flowId"`
	Tags        []string `json:"tags"`
	MatchAll    bool     `json:"matchAll"`
	Search      string   `json:"search"`
	Lim         int32    `json:"lim"`
}

// Tag filter: match_all=false matches ANY of the tags (&&), true requires ALL (@>).
func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Kind,
		arg.Status,
		arg.FlowID,
		arg.Tags,
		arg.MatchAll,
		arg.Search,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Remediation,
			&i.Proof,
			&i.Facts,
			&i.Tags,
			&i.Origin,
			&i.FlowID,
			&i.FlowTitle,
			&i.ProcessID,
			&i.Pid,
			&i.ContextID,
			&i.Error,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesBySubject = `-- name: ListActivitiesBySubject :many
SELECT id, subject_kind, subject_id, kind, status, title, description, remediation, proof, facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error, ref, data, meta, started_at, finished_at, created_at, updated_at FROM activities
WHERE subject_kind = $1 AND subject_id = $2
ORDER BY created_at DESC
`

type ListActivitiesBySubjectParams struct {
	SubjectKind string `json:"subjectKind"`
	SubjectID   int64  `json:"subjectId"`
}

func (q *Queries) ListActivitiesBySubject(ctx context.Context, arg ListActivitiesBySubjectParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesBySubject, arg.SubjectKind, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Remediation,
			&i.Proof,
			&i.Facts,
			&i.Tags,
			&i.Origin,
			&i.FlowID,
			&i.FlowTitle,
			&i.ProcessID,
			&i.Pid,
			&i.ContextID,
			&i.Error,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenActivities = `-- name: ListOpenActivities :many
SELECT id, subject_kind, subject_id, kind, status, title, description, remediation, proof, facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error, ref, data, meta, started_at, finished_at, created_at, updated_at FROM activities
WHERE process_id <> 0 AND status IN ('scheduled', 'running', 'waiting')
ORDER BY created_at ASC
LIMIT $1
`

// Runs still in flight on FloMorphic — what the reconciler polls.
func (q *Queries) ListOpenActivities(ctx context.Context, limit int32) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listOpenActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Remediation,
			&i.Proof,
			&i.Facts,
			&i.Tags,
			&i.Origin,
			&i.FlowID,
			&i.FlowTitle,
			&i.ProcessID,
			&i.Pid,
			&i.ContextID,
			&i.Error,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
   SET subject_kind = $2, subject_id = $3, kind = $4, status = $5, title = $6, description = $7,
       remediation = $8, proof = $9, facts = $10, tags = $11, origin = $12, flow_id = $13,
       flow_title = $14, process_id = $15, pid = $16, context_id = $17, error = $18,
       ref = $19, data = $20, meta = $21, started_at = $22, finished_at = $23,
       updated_at = now()
 WHERE id = $1
RETURNING id, subject_kind, subject_id, kind, status, title, description, remediation, proof, facts, tags, origin, flow_id, flow_title, process_id, pid, context_id, error, ref, data, meta, started_at, finished_at, created_at, updated_at
`

type UpdateActivityParams struct {
	ID          int64           `json:"id"`
	SubjectKind string          `json:"subjectKind"`
	SubjectID   int64           `json:"subjectId"`
	Kind        string          `json:"kind"`
	Status      string          `json:"status"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Remediation string          `json:"remediation"`
	Proof       string          `json:"proof"`
	Facts       json.RawMessage `json:"facts"`
	Tags        []string        `json:"tags"`
	Origin      string          `json:"origin"`
	FlowID      string          `json:"flowId"`
	FlowTitle   string          `json:"flowTitle"`
	ProcessID   int64           `json:"processId"`
	Pid         string          `json:"pid"`
	ContextID   string          `json:"contextId"`
	Error       string          `json:"error"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
	StartedAt   *time.Time      `json:"startedAt"`
	FinishedAt  *time.Time      `json:"finishedAt"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.ID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.Remediation,
		arg.Proof,
		arg.Facts,
		arg.Tags,
		arg.Origin,
		arg.FlowID,
		arg.FlowTitle,
		arg.ProcessID,
		arg.Pid,
		arg.ContextID,
		arg.Error,
		arg.Ref,
		arg.Data,
		arg.Meta,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Remediation,
		&i.Proof,
		&i.Facts,
		&i.Tags,
		&i.Origin,
		&i.FlowID,
		&i.FlowTitle,
		&i.ProcessID,
		&i.Pid,
		&i.ContextID,
		&i.Error,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
