// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charts.sql

package db

import (
	"context"
	"encoding/json"
)

const createChart = `-- name: CreateChart :one
INSERT INTO charts (title, viz_type, query_context, builder_state)
VALUES ($1, $2, $3, $4)
RETURNING id, title, viz_type, query_context, builder_state, created_at, updated_at
`

type CreateChartParams struct {
	Title        string          `json:"title"`
	VizType      string          `json:"vizType"`
	QueryContext json.RawMessage `json:"queryContext"`
	BuilderState json.RawMessage `json:"builderState"`
}

func (q *Queries) CreateChart(ctx context.Context, arg CreateChartParams) (Chart, error) {
	row := q.db.QueryRow(ctx, createChart,
		arg.Title,
		arg.VizType,
		arg.QueryContext,
		arg.BuilderState,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VizType,
		&i.QueryContext,
		&i.BuilderState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChart = `-- name: DeleteChart :exec
DELETE FROM charts WHERE id = $1
`

func (q *Queries) DeleteChart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteChart, id)
	return err
}

const getChart = `-- name: GetChart :one
SELECT id, title, viz_type, query_context, builder_state, created_at, updated_at FROM charts WHERE id = $1
`

func (q *Queries) GetChart(ctx context.Context, id int64) (Chart, error) {
	row := q.db.QueryRow(ctx, getChart, id)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VizType,
		&i.QueryContext,
		&i.BuilderState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharts = `-- name: ListCharts :many
SELECT id, title, viz_type, query_context, builder_state, created_at, updated_at FROM charts ORDER BY updated_at DESC
`

func (q *Queries) ListCharts(ctx context.Context) ([]Chart, error) {
	rows, err := q.db.Query(ctx, listCharts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chart{}
	for rows.Next() {
		var i Chart
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.VizType,
			&i.QueryContext,
			&i.BuilderState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChart = `-- name: UpdateChart :one
UPDATE charts
   SET title = $2, viz_type = $3, query_context = $4, builder_state = $5, updated_at = now()
 WHERE id = $1
RETURNING id, title, viz_type, query_context, builder_state, created_at, updated_at
`

type UpdateChartParams struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	VizType      string          `json:"vizType"`
	QueryContext json.RawMessage `json:"queryContext"`
	BuilderState json.RawMessage `json:"builderState"`
}

func (q *Queries) UpdateChart(ctx context.Context, arg UpdateChartParams) (Chart, error) {
	row := q.db.QueryRow(ctx, updateChart,
		arg.ID,
		arg.Title,
		arg.VizType,
		arg.QueryContext,
		arg.BuilderState,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VizType,
		&i.QueryContext,
		&i.BuilderState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
