// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboards.sql

package db

import (
	"context"
	"encoding/json"
)

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (title, slug, layout)
VALUES ($1, $2, $3)
RETURNING id, title, slug, layout, created_at, updated_at
`

type CreateDashboardParams struct {
	Title  string          `json:"title"`
	Slug   string          `json:"slug"`
	Layout json.RawMessage `json:"layout"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard, arg.Title, arg.Slug, arg.Layout)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboards WHERE id = $1
`

func (q *Queries) DeleteDashboard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDashboard, id)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT id, title, slug, layout, created_at, updated_at FROM dashboards WHERE id = $1
`

func (q *Queries) GetDashboard(ctx context.Context, id int64) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getDashboard, id)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDashboards = `-- name: ListDashboards :many
SELECT id, title, slug, layout, created_at, updated_at FROM dashboards ORDER BY updated_at DESC
`

func (q *Queries) ListDashboards(ctx context.Context) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dashboard{}
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Layout,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :one
UPDATE dashboards
   SET title = $2, slug = $3, layout = $4, updated_at = now()
 WHERE id = $1
RETURNING id, title, slug, layout, created_at, updated_at
`

type UpdateDashboardParams struct {
	ID     int64           `json:"id"`
	Title  string          `json:"title"`
	Slug   string          `json:"slug"`
	Layout json.RawMessage `json:"layout"`
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, updateDashboard,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Layout,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
