// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package db

import (
	"context"
	"encoding/json"
)

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (title, summary, status, severity, confidence, category, tags, source, origin,
                      target, fingerprint, stage_id, issue_id, ref, data, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at
`

type CreateFindingParams struct {
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Status      string          `json:"status"`
	Severity    string          `json:"severity"`
	Confidence  string          `json:"confidence"`
	Category    string          `json:"category"`
	Tags        []string        `json:"tags"`
	Source      string          `json:"source"`
	Origin      string          `json:"origin"`
	Target      string          `json:"target"`
	Fingerprint string          `json:"fingerprint"`
	StageID     int64           `json:"stageId"`
	IssueID     int64           `json:"issueId"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.Title,
		arg.Summary,
		arg.Status,
		arg.Severity,
		arg.Confidence,
		arg.Category,
		arg.Tags,
		arg.Source,
		arg.Origin,
		arg.Target,
		arg.Fingerprint,
		arg.StageID,
		arg.IssueID,
		arg.Ref,
		arg.Data,
		arg.Meta,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Severity,
		&i.Confidence,
		&i.Category,
		&i.Tags,
		&i.Source,
		&i.Origin,
		&i.Target,
		&i.Fingerprint,
		&i.StageID,
		&i.IssueID,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFinding = `-- name: DeleteFinding :exec
DELETE FROM findings WHERE id = $1
`

func (q *Queries) DeleteFinding(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFinding, id)
	return err
}

const findingTags = `-- name: FindingTags :many
SELECT DISTINCT unnest(tags)::text AS tag FROM findings ORDER BY tag
`

func (q *Queries) FindingTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, findingTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinding = `-- name: GetFinding :one
SELECT id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at FROM findings WHERE id = $1
`

func (q *Queries) GetFinding(ctx context.Context, id int64) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Severity,
		&i.Confidence,
		&i.Category,
		&i.Tags,
		&i.Source,
		&i.Origin,
		&i.Target,
		&i.Fingerprint,
		&i.StageID,
		&i.IssueID,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindings = `-- name: ListFindings :many
SELECT id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at FROM findings
WHERE (cardinality($1::text[]) = 0
       OR ($2::bool AND tags @> $1::text[])
       OR (NOT $2::bool AND tags && $1::text[]))
  AND ($3::text = '' OR status = $3::text)
  AND ($4::text = '' OR severity = $4::text)
  AND ($5::text = '' OR category = $5::text)
  AND ($6::text = '' OR source = $6::text)
  AND ($7::text = '' OR target = $7::text)
  AND ($8::text = ''
       OR title ILIKE '%' || $8::text || '%'
       OR summary ILIKE '%' || $8::text || '%'
       OR source ILIKE '%' || $8::text || '%'
       OR origin ILIKE '%' || $8::text || '%'
       OR target ILIKE '%' || $8::text || '%'
       OR fingerprint ILIKE '%' || $8::text || '%')
ORDER BY created_at DESC
`

type ListFindingsParams struct {
	Tags     []string `json:"tags"`
	MatchAll bool     `json:"matchAll"`
	Status   string   `json:"status"`
	Severity string   `json:"severity"`
	Category string   `json:"category"`
	Source   string   `json:"source"`
	Target   string   `json:"target"`
	Search   string   `json:"search"`
}

// Tag filter: match_all=false matches ANY of the tags (&&), true requires ALL (@>).
func (q *Queries) ListFindings(ctx context.Context, arg ListFindingsParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings,
		arg.Tags,
		arg.MatchAll,
		arg.Status,
		arg.Severity,
		arg.Category,
		arg.Source,
		arg.Target,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.Severity,
			&i.Confidence,
			&i.Category,
			&i.Tags,
			&i.Source,
			&i.Origin,
			&i.Target,
			&i.Fingerprint,
			&i.StageID,
			&i.IssueID,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByIssue = `-- name: ListFindingsByIssue :many
SELECT id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at FROM findings WHERE issue_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFindingsByIssue(ctx context.Context, issueID int64) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.Severity,
			&i.Confidence,
			&i.Category,
			&i.Tags,
			&i.Source,
			&i.Origin,
			&i.Target,
			&i.Fingerprint,
			&i.StageID,
			&i.IssueID,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByStage = `-- name: ListFindingsByStage :many
SELECT id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at FROM findings WHERE stage_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFindingsByStage(ctx context.Context, stageID int64) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.Severity,
			&i.Confidence,
			&i.Category,
			&i.Tags,
			&i.Source,
			&i.Origin,
			&i.Target,
			&i.Fingerprint,
			&i.StageID,
			&i.IssueID,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteFinding = `-- name: PromoteFinding :one
UPDATE findings SET status = 'promoted', issue_id = $2, updated_at = now()
 WHERE id = $1
RETURNING id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at
`

type PromoteFindingParams struct {
	ID      int64 `json:"id"`
	IssueID int64 `json:"issueId"`
}

// Record the issue a finding became.
func (q *Queries) PromoteFinding(ctx context.Context, arg PromoteFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, promoteFinding, arg.ID, arg.IssueID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Severity,
		&i.Confidence,
		&i.Category,
		&i.Tags,
		&i.Source,
		&i.Origin,
		&i.Target,
		&i.Fingerprint,
		&i.StageID,
		&i.IssueID,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFinding = `-- name: UpdateFinding :one
UPDATE findings
   SET title = $2, summary = $3, status = $4, severity = $5, confidence = $6, category = $7,
       tags = $8, source = $9, origin = $10, target = $11, fingerprint = $12,
       stage_id = $13, issue_id = $14, ref = $15, data = $16, meta = $17,
       updated_at = now()
 WHERE id = $1
RETURNING id, title, summary, status, severity, confidence, category, tags, source, origin, target, fingerprint, stage_id, issue_id, ref, data, meta, created_at, updated_at
`

type UpdateFindingParams struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Status      string          `json:"status"`
	Severity    string          `json:"severity"`
	Confidence  string          `json:"confidence"`
	Category    string          `json:"category"`
	Tags        []string        `json:"tags"`
	Source      string          `json:"source"`
	Origin      string          `json:"origin"`
	Target      string          `json:"target"`
	Fingerprint string          `json:"fingerprint"`
	StageID     int64           `json:"stageId"`
	IssueID     int64           `json:"issueId"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
}

func (q *Queries) UpdateFinding(ctx context.Context, arg UpdateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, updateFinding,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Status,
		arg.Severity,
		arg.Confidence,
		arg.Category,
		arg.Tags,
		arg.Source,
		arg.Origin,
		arg.Target,
		arg.Fingerprint,
		arg.StageID,
		arg.IssueID,
		arg.Ref,
		arg.Data,
		arg.Meta,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Severity,
		&i.Confidence,
		&i.Category,
		&i.Tags,
		&i.Source,
		&i.Origin,
		&i.Target,
		&i.Fingerprint,
		&i.StageID,
		&i.IssueID,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
