// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Chart struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	VizType      string          `json:"vizType"`
	QueryContext json.RawMessage `json:"queryContext"`
	BuilderState json.RawMessage `json:"builderState"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
}

type Dashboard struct {
	ID        int64           `json:"id"`
	Title     string          `json:"title"`
	Slug      string          `json:"slug"`
	Layout    json.RawMessage `json:"layout"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Issue struct {
	ID        int64           `json:"id"`
	Title     string          `json:"title"`
	Summary   string          `json:"summary"`
	Status    string          `json:"status"`
	Severity  string          `json:"severity"`
	Tags      []string        `json:"tags"`
	Source    string          `json:"source"`
	Assignee  string          `json:"assignee"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Setting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Stage struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Source      string          `json:"source"`
	Disposition string          `json:"disposition"`
	IssueID     int64           `json:"issueId"`
	Tags        []string        `json:"tags"`
	Data        json.RawMessage `json:"data"`
	ReceivedAt  time.Time       `json:"receivedAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}
