// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Chart struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	VizType      string          `json:"vizType"`
	QueryContext json.RawMessage `json:"queryContext"`
	BuilderState json.RawMessage `json:"builderState"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
}

type Dashboard struct {
	ID        int64           `json:"id"`
	Title     string          `json:"title"`
	Slug      string          `json:"slug"`
	Layout    json.RawMessage `json:"layout"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Setting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updatedAt"`
}
