// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Activity struct {
	ID          int64           `json:"id"`
	SubjectKind string          `json:"subjectKind"`
	SubjectID   int64           `json:"subjectId"`
	Kind        string          `json:"kind"`
	Status      string          `json:"status"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Remediation string          `json:"remediation"`
	Proof       string          `json:"proof"`
	Facts       json.RawMessage `json:"facts"`
	Tags        []string        `json:"tags"`
	Origin      string          `json:"origin"`
	FlowID      string          `json:"flowId"`
	FlowTitle   string          `json:"flowTitle"`
	ProcessID   int64           `json:"processId"`
	Pid         string          `json:"pid"`
	ContextID   string          `json:"contextId"`
	Error       string          `json:"error"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
	StartedAt   *time.Time      `json:"startedAt"`
	FinishedAt  *time.Time      `json:"finishedAt"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type Chart struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	VizType      string          `json:"vizType"`
	QueryContext json.RawMessage `json:"queryContext"`
	BuilderState json.RawMessage `json:"builderState"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
}

type Dashboard struct {
	ID        int64           `json:"id"`
	Title     string          `json:"title"`
	Slug      string          `json:"slug"`
	Layout    json.RawMessage `json:"layout"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Finding struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Status      string          `json:"status"`
	Severity    string          `json:"severity"`
	Confidence  string          `json:"confidence"`
	Category    string          `json:"category"`
	Tags        []string        `json:"tags"`
	Source      string          `json:"source"`
	Origin      string          `json:"origin"`
	Target      string          `json:"target"`
	Fingerprint string          `json:"fingerprint"`
	StageID     int64           `json:"stageId"`
	IssueID     int64           `json:"issueId"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type Issue struct {
	ID        int64           `json:"id"`
	Title     string          `json:"title"`
	Summary   string          `json:"summary"`
	Status    string          `json:"status"`
	Severity  string          `json:"severity"`
	Tags      []string        `json:"tags"`
	Source    string          `json:"source"`
	Origin    string          `json:"origin"`
	Assignee  string          `json:"assignee"`
	FindingID int64           `json:"findingId"`
	StageID   int64           `json:"stageId"`
	Ref       json.RawMessage `json:"ref"`
	Data      json.RawMessage `json:"data"`
	Meta      json.RawMessage `json:"meta"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Setting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type Stage struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Source      string          `json:"source"`
	Origin      string          `json:"origin"`
	Disposition string          `json:"disposition"`
	FindingID   int64           `json:"findingId"`
	IssueID     int64           `json:"issueId"`
	Tags        []string        `json:"tags"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
	ReceivedAt  time.Time       `json:"receivedAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}
