// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"
	"encoding/json"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (key, name, version, description, tags, scale, manifest, files, source, params, secrets, bindings)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, key, name, version, description, tags, scale, manifest, files, source, params, secrets, bindings, installed_at, updated_at
`

type CreateOperationParams struct {
	Key         string          `json:"key"`
	Name        string          `json:"name"`
	Version     string          `json:"version"`
	Description string          `json:"description"`
	Tags        []string        `json:"tags"`
	Scale       []string        `json:"scale"`
	Manifest    json.RawMessage `json:"manifest"`
	Files       json.RawMessage `json:"files"`
	Source      json.RawMessage `json:"source"`
	Params      json.RawMessage `json:"params"`
	Secrets     json.RawMessage `json:"secrets"`
	Bindings    json.RawMessage `json:"bindings"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.Key,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Tags,
		arg.Scale,
		arg.Manifest,
		arg.Files,
		arg.Source,
		arg.Params,
		arg.Secrets,
		arg.Bindings,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Tags,
		&i.Scale,
		&i.Manifest,
		&i.Files,
		&i.Source,
		&i.Params,
		&i.Secrets,
		&i.Bindings,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOperation = `-- name: DeleteOperation :exec
DELETE FROM operations WHERE id = $1
`

func (q *Queries) DeleteOperation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOperation, id)
	return err
}

const getOperation = `-- name: GetOperation :one
SELECT id, key, name, version, description, tags, scale, manifest, files, source, params, secrets, bindings, installed_at, updated_at FROM operations WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id int64) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Tags,
		&i.Scale,
		&i.Manifest,
		&i.Files,
		&i.Source,
		&i.Params,
		&i.Secrets,
		&i.Bindings,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationByKey = `-- name: GetOperationByKey :one
SELECT id, key, name, version, description, tags, scale, manifest, files, source, params, secrets, bindings, installed_at, updated_at FROM operations WHERE key = $1
`

func (q *Queries) GetOperationByKey(ctx context.Context, key string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByKey, key)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Tags,
		&i.Scale,
		&i.Manifest,
		&i.Files,
		&i.Source,
		&i.Params,
		&i.Secrets,
		&i.Bindings,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperations = `-- name: ListOperations :many
SELECT id, key, name, version, description, tags, scale, manifest, files, source, params, secrets, bindings, installed_at, updated_at FROM operations ORDER BY name ASC, id ASC
`

func (q *Queries) ListOperations(ctx context.Context) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Tags,
			&i.Scale,
			&i.Manifest,
			&i.Files,
			&i.Source,
			&i.Params,
			&i.Secrets,
			&i.Bindings,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperation = `-- name: UpdateOperation :one
UPDATE operations
   SET name = $2, version = $3, description = $4, tags = $5, scale = $6, manifest = $7, files = $8,
       source = $9, params = $10, secrets = $11, bindings = $12, updated_at = now()
 WHERE id = $1
RETURNING id, key, name, version, description, tags, scale, manifest, files, source, params, secrets, bindings, installed_at, updated_at
`

type UpdateOperationParams struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Version     string          `json:"version"`
	Description string          `json:"description"`
	Tags        []string        `json:"tags"`
	Scale       []string        `json:"scale"`
	Manifest    json.RawMessage `json:"manifest"`
	Files       json.RawMessage `json:"files"`
	Source      json.RawMessage `json:"source"`
	Params      json.RawMessage `json:"params"`
	Secrets     json.RawMessage `json:"secrets"`
	Bindings    json.RawMessage `json:"bindings"`
}

func (q *Queries) UpdateOperation(ctx context.Context, arg UpdateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, updateOperation,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Tags,
		arg.Scale,
		arg.Manifest,
		arg.Files,
		arg.Source,
		arg.Params,
		arg.Secrets,
		arg.Bindings,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Tags,
		&i.Scale,
		&i.Manifest,
		&i.Files,
		&i.Source,
		&i.Params,
		&i.Secrets,
		&i.Bindings,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}
