// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage.sql

package db

import (
	"context"
	"encoding/json"
)

const createStage = `-- name: CreateStage :one
INSERT INTO stage (title, summary, source, origin, disposition, tags, ref, data, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, summary, source, origin, disposition, finding_id, issue_id, tags, ref, data, meta, received_at, updated_at
`

type CreateStageParams struct {
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Source      string          `json:"source"`
	Origin      string          `json:"origin"`
	Disposition string          `json:"disposition"`
	Tags        []string        `json:"tags"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.Title,
		arg.Summary,
		arg.Source,
		arg.Origin,
		arg.Disposition,
		arg.Tags,
		arg.Ref,
		arg.Data,
		arg.Meta,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Origin,
		&i.Disposition,
		&i.FindingID,
		&i.IssueID,
		&i.Tags,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :exec
DELETE FROM stage WHERE id = $1
`

func (q *Queries) DeleteStage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStage, id)
	return err
}

const getStage = `-- name: GetStage :one
SELECT id, title, summary, source, origin, disposition, finding_id, issue_id, tags, ref, data, meta, received_at, updated_at FROM stage WHERE id = $1
`

func (q *Queries) GetStage(ctx context.Context, id int64) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Origin,
		&i.Disposition,
		&i.FindingID,
		&i.IssueID,
		&i.Tags,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStage = `-- name: ListStage :many
SELECT id, title, summary, source, origin, disposition, finding_id, issue_id, tags, ref, data, meta, received_at, updated_at FROM stage
WHERE (cardinality($1::text[]) = 0
       OR ($2::bool AND tags @> $1::text[])
       OR (NOT $2::bool AND tags && $1::text[]))
  AND ($3::text = '' OR disposition = $3::text)
  AND ($4::text = '' OR source = $4::text)
  AND ($5::text = ''
       OR title ILIKE '%' || $5::text || '%'
       OR summary ILIKE '%' || $5::text || '%'
       OR source ILIKE '%' || $5::text || '%'
       OR origin ILIKE '%' || $5::text || '%')
ORDER BY received_at DESC
`

type ListStageParams struct {
	Tags        []string `json:"tags"`
	MatchAll    bool     `json:"matchAll"`
	Disposition string   `json:"disposition"`
	Source      string   `json:"source"`
	Search      string   `json:"search"`
}

// Filter by tags (empty = no tag filter). match_all=false matches ANY of the
// tags (overlap, &&); match_all=true requires ALL of them (contains, @>) — the
// same semantics as ListIssues / ListFindings.
func (q *Queries) ListStage(ctx context.Context, arg ListStageParams) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStage,
		arg.Tags,
		arg.MatchAll,
		arg.Disposition,
		arg.Source,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Source,
			&i.Origin,
			&i.Disposition,
			&i.FindingID,
			&i.IssueID,
			&i.Tags,
			&i.Ref,
			&i.Data,
			&i.Meta,
			&i.ReceivedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteStage = `-- name: PromoteStage :one
UPDATE stage
   SET disposition = 'promoted',
       finding_id = CASE WHEN $1::bigint = 0 THEN finding_id ELSE $1::bigint END,
       issue_id   = CASE WHEN $2::bigint   = 0 THEN issue_id   ELSE $2::bigint   END,
       updated_at = now()
 WHERE id = $3
RETURNING id, title, summary, source, origin, disposition, finding_id, issue_id, tags, ref, data, meta, received_at, updated_at
`

type PromoteStageParams struct {
	FindingID int64 `json:"findingId"`
	IssueID   int64 `json:"issueId"`
	ID        int64 `json:"id"`
}

// Mark a staged row as promoted and record what it became: a finding, an
// issue, or both (0 leaves a link untouched).
func (q *Queries) PromoteStage(ctx context.Context, arg PromoteStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, promoteStage, arg.FindingID, arg.IssueID, arg.ID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Origin,
		&i.Disposition,
		&i.FindingID,
		&i.IssueID,
		&i.Tags,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stageTags = `-- name: StageTags :many
SELECT DISTINCT unnest(tags)::text AS tag FROM stage ORDER BY tag
`

// Distinct tags across the inbox, for the tag picker when defining a view.
func (q *Queries) StageTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, stageTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStage = `-- name: UpdateStage :one
UPDATE stage
   SET title = $2, summary = $3, source = $4, origin = $5, disposition = $6,
       finding_id = $7, issue_id = $8, tags = $9, ref = $10, data = $11, meta = $12,
       updated_at = now()
 WHERE id = $1
RETURNING id, title, summary, source, origin, disposition, finding_id, issue_id, tags, ref, data, meta, received_at, updated_at
`

type UpdateStageParams struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Source      string          `json:"source"`
	Origin      string          `json:"origin"`
	Disposition string          `json:"disposition"`
	FindingID   int64           `json:"findingId"`
	IssueID     int64           `json:"issueId"`
	Tags        []string        `json:"tags"`
	Ref         json.RawMessage `json:"ref"`
	Data        json.RawMessage `json:"data"`
	Meta        json.RawMessage `json:"meta"`
}

// Full-row update of the editable columns; the handler merges a partial body
// onto the current row first, so this always writes every field.
func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, updateStage,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Source,
		arg.Origin,
		arg.Disposition,
		arg.FindingID,
		arg.IssueID,
		arg.Tags,
		arg.Ref,
		arg.Data,
		arg.Meta,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Origin,
		&i.Disposition,
		&i.FindingID,
		&i.IssueID,
		&i.Tags,
		&i.Ref,
		&i.Data,
		&i.Meta,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}
