// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage.sql

package db

import (
	"context"
	"encoding/json"
)

const createStage = `-- name: CreateStage :one
INSERT INTO stage (title, summary, source, disposition, tags, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, summary, source, disposition, issue_id, tags, data, received_at, updated_at
`

type CreateStageParams struct {
	Title       string          `json:"title"`
	Summary     string          `json:"summary"`
	Source      string          `json:"source"`
	Disposition string          `json:"disposition"`
	Tags        []string        `json:"tags"`
	Data        json.RawMessage `json:"data"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.Title,
		arg.Summary,
		arg.Source,
		arg.Disposition,
		arg.Tags,
		arg.Data,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Disposition,
		&i.IssueID,
		&i.Tags,
		&i.Data,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStage = `-- name: GetStage :one
SELECT id, title, summary, source, disposition, issue_id, tags, data, received_at, updated_at
FROM stage WHERE id = $1
`

func (q *Queries) GetStage(ctx context.Context, id int64) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Disposition,
		&i.IssueID,
		&i.Tags,
		&i.Data,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStage = `-- name: ListStage :many
SELECT id, title, summary, source, disposition, issue_id, tags, data, received_at, updated_at
FROM stage
WHERE ($1::text = '' OR disposition = $1::text)
  AND ($2::text = '' OR source = $2::text)
  AND ($3::text = ''
       OR title ILIKE '%' || $3::text || '%'
       OR summary ILIKE '%' || $3::text || '%'
       OR source ILIKE '%' || $3::text || '%')
ORDER BY received_at DESC
`

type ListStageParams struct {
	Disposition string `json:"disposition"`
	Source      string `json:"source"`
	Search      string `json:"search"`
}

func (q *Queries) ListStage(ctx context.Context, arg ListStageParams) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStage, arg.Disposition, arg.Source, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Source,
			&i.Disposition,
			&i.IssueID,
			&i.Tags,
			&i.Data,
			&i.ReceivedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteStage = `-- name: PromoteStage :one
UPDATE stage SET disposition = 'promoted', issue_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, summary, source, disposition, issue_id, tags, data, received_at, updated_at
`

type PromoteStageParams struct {
	ID      int64 `json:"id"`
	IssueID int64 `json:"issueId"`
}

// Mark a staged row as promoted and record the issue it became.
func (q *Queries) PromoteStage(ctx context.Context, arg PromoteStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, promoteStage, arg.ID, arg.IssueID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Source,
		&i.Disposition,
		&i.IssueID,
		&i.Tags,
		&i.Data,
		&i.ReceivedAt,
		&i.UpdatedAt,
	)
	return i, err
}
