// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package db

import (
	"context"
)

const createView = `-- name: CreateView :one
INSERT INTO views (name, target, tags, match_mode)
VALUES ($1, $2, $3, $4)
RETURNING id, name, target, tags, match_mode, created_at, updated_at
`

type CreateViewParams struct {
	Name      string   `json:"name"`
	Target    string   `json:"target"`
	Tags      []string `json:"tags"`
	MatchMode string   `json:"matchMode"`
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRow(ctx, createView,
		arg.Name,
		arg.Target,
		arg.Tags,
		arg.MatchMode,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Tags,
		&i.MatchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM views WHERE id = $1
`

func (q *Queries) DeleteView(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteView, id)
	return err
}

const getView = `-- name: GetView :one
SELECT id, name, target, tags, match_mode, created_at, updated_at FROM views WHERE id = $1
`

func (q *Queries) GetView(ctx context.Context, id int64) (View, error) {
	row := q.db.QueryRow(ctx, getView, id)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Tags,
		&i.MatchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViews = `-- name: ListViews :many
SELECT id, name, target, tags, match_mode, created_at, updated_at FROM views
WHERE ($1::text = '' OR target = $1::text)
ORDER BY created_at
`

// Every saved view, oldest first so the sidebar order is stable as views are added.
func (q *Queries) ListViews(ctx context.Context, target string) ([]View, error) {
	rows, err := q.db.Query(ctx, listViews, target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []View{}
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Target,
			&i.Tags,
			&i.MatchMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateView = `-- name: UpdateView :one
UPDATE views
   SET name = $2, target = $3, tags = $4, match_mode = $5, updated_at = now()
 WHERE id = $1
RETURNING id, name, target, tags, match_mode, created_at, updated_at
`

type UpdateViewParams struct {
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	Target    string   `json:"target"`
	Tags      []string `json:"tags"`
	MatchMode string   `json:"matchMode"`
}

// Full-row update of the editable columns; the handler merges a partial body
// onto the current row first, so this always writes every field.
func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) (View, error) {
	row := q.db.QueryRow(ctx, updateView,
		arg.ID,
		arg.Name,
		arg.Target,
		arg.Tags,
		arg.MatchMode,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Target,
		&i.Tags,
		&i.MatchMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
